<a href="https://colab.research.google.com/github/Gursewak-S/Advance-Python/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Panda => pandas is an open-source library that is used for handle data manipulation.

In [ ]:
# for installing

!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# Data Structure of Pandas :
# (1). Series •--› It is one-dimensional array and it shows only values not column name.
# (2). DataFrame --› It is multi-dimensional array and it shows values with column name .

# (1). Series

In [ ]:
import pandas as pd

In [ ]:
a = pd.Series([1,65,34,800])
a

0      1
1     65
2     34
3    800
dtype: int64

In [ ]:
type(a)

pandas.core.series.Series

# (2). DataFrame

In [ ]:
# Q.1 We have to create employee data using dictionary ?

a = {
    "Emp_ID": [1, 2,3,4,5,6,7,8],
    "Emp Name": ['Sam', 'Raj', 'Mohit', 'Sam', 'Gorav', 'Mohit', 'Mohit', 'Garvit'],
    "Department": ['IT', 'Sales', 'IT', 'Operations', 'HR', 'IT', 'Operations', 'HR'],
    "Working_hours": [8,9,9,9,9,8,8,8],
    "Salary": [23000,25000,35000,31000,28000,26000, 30000, 34000]
}

In [ ]:
type(a)

dict

In [ ]:
df = pd.DataFrame(a)
df

   Emp_ID Emp Name  Department  Working_hours  Salary
0       1      Sam          IT              8   23000
1       2      Raj       Sales              9   25000
2       3    Mohit          IT              9   35000
3       4      Sam  Operations              9   31000
4       5    Gorav          HR              9   28000
5       6    Mohit          IT              8   26000
6       7    Mohit  Operations              8   30000
7       8   Garvit          HR              8   34000

# How do you export our dataframe into csv file? (Jupiter)

In [ ]:
# df.to_csv("file_location", index =False)

# HOW DO YOU IMPORT OUR DATAFRAME INTO JUPYTER NOTEBOOK ?

In [ ]:
# open a folder in which you have datasets .
# copy the folder Location
# paste it into jupyternotebook
# df = pd.read_csv("paste_folder_location//file_name.csv")

Method 1

In [ ]:
# df = pd.read_csv("File_location")
# df

Method 2

In [ ]:
# Go to home page of jupyter .
# click on upload.
# click on open --› upload.
# pd.read_csv("fiLename.csv")

In [ ]:
# df = pd.read_csv("cars.csv")
# df

# How do you export our dataframe into csv file? (Collab)

In [13]:
df.to_csv("/content/emp.csv")

# Import

In [17]:
a = pd.read_csv("/content/emp.csv")
a

   Unnamed: 0  Emp_ID Emp Name  Department  Working_hours  Salary
0           0       1      Sam          IT              8   23000
1           1       2      Raj       Sales              9   25000
2           2       3    Mohit          IT              9   35000
3           3       4      Sam  Operations              9   31000
4           4       5    Gorav          HR              9   28000
5           5       6    Mohit          IT              8   26000
6           6       7    Mohit  Operations              8   30000
7           7       8   Garvit          HR              8   34000